### PR TITLE
Added in a handful of physical constants/units and J_n(x)

### PR DESCRIPTION
**Pull request by zeotherm**
Added in a handful of the physical constants you were looking for, as well as an implementation of the Bessel J function of any order.  Can't test however, because I don't have your key file to check the signing against.  Hope this helps, or you can kick me a key file for more testing.

### CODE REVIEW

**Comment by mariuszgromada** [comment]
Thx :-) Will work a bit o that to create java code.

**Comment by mariuszgromada** [comment]
@zeotherm Thx for your contribution. I just realized that you did not appear in the mXparser's contributors list
https://github.com/mariuszgromada/MathParser.org-mXparser/graphs/contributors

which is a pitty. Pls check if your commit was made with the same email address the is associated to your GitHub account. Your email address that was used in the commit you cna check here

https://github.com/mariuszgromada/MathParser.org-mXparser/commit/37a19d118250aa4c76f62f6ee5dbab525bc684b6.patch

Best regards

**Comment by mariuszgromada** [comment]
@zeotherm I have already check this - this is your email issue, you have different on commits and registered in your GitHub profile.

**Comment by zeotherm** [comment]
@mariuszgromada Yeah, oops.  That was from my work account, I forgot what I was logged into.  I added my work e-mail to associate with this GitHub account, so hopefully that will fix things for the time being.  Let me know if this doesn't fix things.  Thanks.

**Pull request merged**
